In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
nested_list = [[1,2],
               [3,4],
               [5,6]]

In [5]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [6]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(3)

array([0.6252423 , 0.44512999, 0.29004379])

In [21]:
np.random.rand(3,3)#uniform distrobution

array([[0.0832712 , 0.87993117, 0.76613351],
       [0.70806305, 0.54808411, 0.01498412],
       [0.04401082, 0.00302153, 0.46229197]])

In [22]:
np.random.randn(3,3)#standard distrobution->mean=0 and variance = 1

array([[-0.63523003,  0.2678332 ,  0.14389644],
       [ 0.4426565 , -0.74635596, -1.06030633],
       [ 0.15046551,  0.07386876,  1.1226112 ]])

In [23]:
np.random.randint(1,100)

23

In [25]:
np.random.randint(1,100,(3,3))

array([[76,  2, 15],
       [75,  2, 39],
       [ 5, 75, 53]])

In [26]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [27]:
arr = np.random.randint(1,100,25)

In [28]:
arr

array([83, 87, 75, 75, 88, 24,  3, 22, 53,  2, 88, 30, 38,  2, 64, 60, 21,
       33, 76, 58, 22, 89, 49, 91, 59])

In [29]:
arr.shape

(25,)

In [30]:
arr.reshape(5,5)#cannot give a shape that contains more or less elements than 25

array([[83, 87, 75, 75, 88],
       [24,  3, 22, 53,  2],
       [88, 30, 38,  2, 64],
       [60, 21, 33, 76, 58],
       [22, 89, 49, 91, 59]])

In [31]:
arr.max()

91

In [32]:
arr.argmax()#index of the max value

23

In [33]:
arr.min()

2

In [34]:
arr.argmin()#index of the min value

9

In [36]:
arr.dtype

dtype('int64')

In [37]:
arr = np.arange(1,11)

In [38]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[9]

10

In [40]:
arr[1:5]

array([2, 3, 4, 5])

# array boardcasting


In [41]:
arr[0:5] = 100

In [42]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [43]:
array_slice = arr[0:4]

In [44]:
array_slice[:] = 200

In [45]:
array_slice

array([200, 200, 200, 200])

In [46]:
arr

array([200, 200, 200, 200, 100,   6,   7,   8,   9,  10])

In [47]:
array_copy = arr.copy()#for not changing the actual array

In [49]:
array_copy[:] = 300

In [50]:
arr

array([200, 200, 200, 200, 100,   6,   7,   8,   9,  10])

In [51]:
arr_2d = np.array([[2,3,4],[5,6,7],[8,9,10]])

In [52]:
arr_2d

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [53]:
arr_2d.shape

(3, 3)

In [54]:
arr_2d[2]

array([ 8,  9, 10])

In [55]:
arr_2d[0,2]

4

In [56]:
arr_2d[0:1,1:3]

array([[3, 4]])

In [59]:
arr >100

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [60]:
bool_arr = arr>100

In [61]:
arr[bool_arr]

array([200, 200, 200, 200])

In [2]:
arr = np.arange(0,11)

In [3]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
arr -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr / arr

<ipython-input-9-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
1/0

ZeroDivisionError: ignored

In [11]:
1/arr

<ipython-input-11-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [13]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [14]:
np.log(arr)

<ipython-input-14-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [15]:
arr.mean()

5.0

In [16]:
arr.max()

10

In [17]:
arr.std()

3.1622776601683795

In [18]:
arr.var()

10.0

In [19]:
arr.sum()

55

In [20]:
arr2d = np.arange(0,25).reshape(5,5)

In [21]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
arr2d.sum()

300

In [23]:
arr2d.sum(axis=0)#do sum across rows->(5!,5)-> summing the columns

array([50, 55, 60, 65, 70])

In [ ]:
arr2d.sum(axis=1)#do sum across columns->(5,5!)-> summing the rows